version: 1.0.{build}
image: Visual Studio 2017
before_build:
 - appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
on_success:
 - nuget install Hub-Nuget -Pre
 - Hub-NuGet.1.0.0-beta\tools\buildBom.exe --hub_deploy_bdio=false
 - curl -s https://test.duckbuild.io/batch/appveyor > appveyor.bat
 - appveyor
